# Generated by Django 4.2.20 on 2025-04-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diaryentry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='categories',
            field=models.ManyToManyField(blank=True, to='diary.category'),
        ),
    ]
