# Generated by Django 5.2 on 2025-04-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_category_diaryentry_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
