# Generated by Django 5.2 on 2025-04-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diaryentry_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diary_images/'),
        ),
    ]
